#
# MIT License
#
# Copyright(c) 2011-2020 The Maintainers of Nanvix
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

sudo: required

language: C

services:
- docker

env:
  global:
      - SSH_KEY=ssh/travis_multikernel_rsa.enc
      - SSH_CONFIG=ssh/config
      - SERVER_NAME=mppa

jobs:
  include:
    # Build Debug
    - stage: "Build Debug"
      name: "Unix 64-bit"
      script: docker run -v "$(pwd):/mnt" -p 4567:4567 nanvix/ubuntu:unix64        /bin/bash -l -c "cd /mnt && make contrib && make all"
    - stage: "Build Debug"
      name: "MPPA-256"
      if: (NOT type IN (pull_request))
      before_script:
        - openssl aes-256-cbc -K $encrypted_2341a3c09029_key -iv $encrypted_2341a3c09029_iv -in $SSH_KEY -out travis_multikernel_rsa -d
        - eval "$(ssh-agent -s)"
        - chmod 600 travis_multikernel_rsa
        - cp $SSH_CONFIG ~/.ssh/config
        - ssh-add travis_multikernel_rsa
      script:
        - rsync -avz --delete-after --exclude=".git" . $SERVER_NAME:~/travis/multikernel
        - ssh $SERVER_NAME 'bash travis/build-multikernel.sh --no-verbose --debug'

    # Build Release
    - stage: "Build Release"
      name: "Unix 64-bit"
      script: docker run -v "$(pwd):/mnt" -p 4567:4567 nanvix/ubuntu:unix64        /bin/bash -l -c "cd /mnt && export RELEASE=true && make contrib && make all"
    - stage: "Build Release"
      name: "MPPA-256"
      if: (NOT type IN (pull_request))
      before_script:
        - openssl aes-256-cbc -K $encrypted_2341a3c09029_key -iv $encrypted_2341a3c09029_iv -in $SSH_KEY -out travis_multikernel_rsa -d
        - eval "$(ssh-agent -s)"
        - chmod 600 travis_multikernel_rsa
        - cp $SSH_CONFIG ~/.ssh/config
        - ssh-add travis_multikernel_rsa
      script:
        - rsync -avz --delete-after --exclude=".git" . $SERVER_NAME:~/travis/multikernel
        - ssh $SERVER_NAME 'bash travis/build-multikernel.sh --no-verbose --release'

notifications:
  slack: nanvix:31ePVjsrXynUajPUDqy6I0hp
